### ISSUE TITLE
PHP8.1 usage

### ISSUE THREAD

**Issue by dpslwk** [nateobray/IPP#6]
Trying to use this will PHP8.1
getting a lot of deprecation warnings for `obray/ipp`, `obray\http` and `obray/http-client`

have over the main show stopper is 
`Fatal error: Uncaught TypeError: stream_select(): supplied argument is not a valid stream resource`
and 
`Next ValueError: No stream arrays were passed`

<details>
<summary>test code</summary>
<p>

```
<?php

$loader = require_once 'vendor/autoload.php';

use obray\ipp\Printer;

$printer = new Printer(
    'ipp://192.168.15.14:631/ipp',
    // {username}, // optional
    // {password}  // optional
);

var_dump($printer);
$attributes = $printer->getPrinterAttributes();
var_dump($attributes);
$jobs = $printer->getJobs();
var_dump($jobs);
```

</p>
</details>

<details><summary>Full Console dump of errors</summary>
<p>

```
$php index.php                                        
object(obray\ipp\Printer)#3 (6) {
  ["ipp":"obray\ipp\Printer":private]=>
  NULL
  ["printerURI":"obray\ipp\Printer":private]=>
  string(27) "ipp://192.168.15.14:631/ipp"
  ["user":"obray\ipp\Printer":private]=>
  string(0) ""
  ["password":"obray\ipp\Printer":private]=>
  string(0) ""
  ["lastRequest":"obray\ipp\Printer":private]=>
  NULL
  ["lastResponse":"obray\ipp\Printer":private]=>
  NULL
}

Deprecated: Return type of obray\ipp\AttributeGroup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/AttributeGroup.php on line 113

Deprecated: Return type of obray\ipp\Attribute::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/Attribute.php on line 106

Deprecated: Return type of obray\ipp\types\basic\SignedShort::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/types/basic/SignedShort.php on line 58

Deprecated: Return type of obray\ipp\types\basic\LocalizedString::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/types/basic/LocalizedString.php on line 60

Deprecated: Return type of obray\ipp\types\basic\USASCIIString::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/types/basic/USASCIIString.php on line 48

Deprecated: Return type of obray\ipp\types\VersionNumber::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/types/VersionNumber.php on line 39

Deprecated: Return type of obray\ipp\types\basic\SignedInteger::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/src/types/basic/SignedInteger.php on line 53

Deprecated: Return type of obray\http\Headers::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http/src/Headers.php on line 88

Deprecated: Return type of obray\http\Headers::next() should either be compatible with Iterator::next(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http/src/Headers.php on line 96

Deprecated: Return type of obray\http\Headers::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http/src/Headers.php on line 92

Deprecated: Return type of obray\http\Headers::valid() should either be compatible with Iterator::valid(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http/src/Headers.php on line 100

Deprecated: Return type of obray\http\Headers::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http/src/Headers.php on line 84

Deprecated: Optional parameter $method declared before required parameter $url is implicitly treated as a required parameter in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http-client/src/handlers/HTTPClientHandler.php on line 17

Fatal error: Uncaught TypeError: stream_select(): supplied argument is not a valid stream resource in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-server/src/eventLoops/StreamSelectEventLoop.php:29
Stack trace:
#0 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-server/src/eventLoops/StreamSelectEventLoop.php(29): stream_select(Array, NULL, NULL, 0, 0)
#1 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-client/src/SocketClient.php(117): obray\eventLoops\StreamSelectEventLoop->run()
#2 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-client/src/SocketClient.php(86): obray\SocketClient->watch()
#3 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http-client/src/HTTPClient.php(25): obray\SocketClient->connect(Object(obray\handlers\HTTPClientHandler))
#4 /Users/matt/Dropbox/Work/Brisco/github/IPP/src/Request.php(42): obray\HTTPClient::post('http://192.168....', '\x01\x01\x00\v\x00\x00\x00\x01\x01G\x00\x12att...', Object(obray\http\Headers))
#5 /Users/matt/Dropbox/Work/Brisco/github/IPP/src/Printer.php(187): obray\ipp\Request::send('ipp://192.168.1...', '\x01\x01\x00\v\x00\x00\x00\x01\x01G\x00\x12att...', '', '')
#6 /Users/matt/Dropbox/Work/Brisco/github/IPP/index.php(14): obray\ipp\Printer->getPrinterAttributes()
#7 {main}

Next ValueError: No stream arrays were passed in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-server/src/eventLoops/StreamSelectEventLoop.php:29
Stack trace:
#0 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-server/src/eventLoops/StreamSelectEventLoop.php(29): stream_select(Array, NULL, NULL, 0, 0)
#1 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-client/src/SocketClient.php(117): obray\eventLoops\StreamSelectEventLoop->run()
#2 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-client/src/SocketClient.php(86): obray\SocketClient->watch()
#3 /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/http-client/src/HTTPClient.php(25): obray\SocketClient->connect(Object(obray\handlers\HTTPClientHandler))
#4 /Users/matt/Dropbox/Work/Brisco/github/IPP/src/Request.php(42): obray\HTTPClient::post('http://192.168....', '\x01\x01\x00\v\x00\x00\x00\x01\x01G\x00\x12att...', Object(obray\http\Headers))
#5 /Users/matt/Dropbox/Work/Brisco/github/IPP/src/Printer.php(187): obray\ipp\Request::send('ipp://192.168.1...', '\x01\x01\x00\v\x00\x00\x00\x01\x01G\x00\x12att...', '', '')
#6 /Users/matt/Dropbox/Work/Brisco/github/IPP/index.php(14): obray\ipp\Printer->getPrinterAttributes()
#7 {main}
  thrown in /Users/matt/Dropbox/Work/Brisco/github/IPP/vendor/obray/socket-server/src/eventLoops/StreamSelectEventLoop.php on line 29

```
</p>
</details>

**Comment by nateobray** [comment]
Let me have a look and I'll follow up.  Thanks!

**Comment by adam1658** [comment]
I'm using guzzle to get it working with PHP 8.1. I've only done enough to get it working with a single `$printer->printJob(...)` call. I'm using [cweagans/composer-patches](https://packagist.org/packages/cweagans/composer-patches) to apply patches.

Update composer.json as follows:
```json
    // Don't install obray/http-client and it's dependencies
    "replace": {
        "obray/http-client": "*"
    },

    // Apply patches to obray/ipp
    "extra": {
        "patches": {
            "obray/ipp": {
                "Use Guzzle for HTTP": "patches/obray/ipp-guzzle.patch",
                "PHP 8.1 compatibility": "patches/obray/ipp-php81.patch"
            }
        }
    }
```

The patches are as follows:
ipp-guzzle.patch:
```diff
diff --color -ur a/src/Request.php b/src/Request.php
--- a/src/Request.php	2022-09-08 10:01:41.038637000 +1000
+++ b/src/Request.php	2022-09-08 10:05:17.651672000 +1000
@@ -39,13 +39,20 @@
             $headers["Authorization"] = "Basic " . base64_encode($user.':'.$password);
         }
 
-        $response = \obray\HTTPClient::post($postURL, $encodedPayload, $headers);
+        $client = new \GuzzleHttp\Client();
+        $response = $client->post(
+            $postURL,
+            [
+                'headers' => $headers,
+                'body' => $encodedPayload,
+            ],
+        );
         if($response->getStatusCode() == 401) throw new \obray\ipp\exceptions\AuthenticationError();
         if($response->getStatusCode() !== 200) throw new \obray\ipp\exceptions\HTTPError($response->getStatusCode());
         
         // parse the response
         $responsePayload = new \obray\ipp\transport\IPPPayload();
-        $responsePayload->decode($response->getBody()->encode());
+        $responsePayload->decode($response->getBody()->getContents());
         
         return $responsePayload;
     }
```


ipp-php81.patch:
```diff
diff --color -ur a/src/Attribute.php b/src/Attribute.php
--- a/src/Attribute.php	2022-09-08 11:08:04.354359000 +1000
+++ b/src/Attribute.php	2022-09-08 11:08:32.355780000 +1000
@@ -103,7 +103,7 @@
         return $this->offset;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->value;
     }
diff --color -ur a/src/AttributeGroup.php b/src/AttributeGroup.php
--- a/src/AttributeGroup.php	2022-09-08 11:08:04.354359000 +1000
+++ b/src/AttributeGroup.php	2022-09-08 11:08:21.734359000 +1000
@@ -110,7 +110,7 @@
         }
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->attributes;
     }
diff --color -ur a/src/CollectionAttribute.php b/src/CollectionAttribute.php
--- a/src/CollectionAttribute.php	2022-09-08 11:08:04.354359000 +1000
+++ b/src/CollectionAttribute.php	2022-09-08 11:09:08.917120000 +1000
@@ -146,7 +146,7 @@
         return $this;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->getArray();
     }
diff --color -ur a/src/enums/Types.php b/src/enums/Types.php
--- a/src/enums/Types.php	2022-09-08 11:08:04.364359000 +1000
+++ b/src/enums/Types.php	2022-09-08 11:12:18.710813000 +1000
@@ -97,15 +97,15 @@
                 return new \obray\ipp\types\OctetString($value);
                 break;
             case \obray\ipp\enums\Types::RANGEOFINTEGER:
-                $value = explode('-',$value);
-                if(count($value)!=2){
+                $value = $value === null ? false : explode('-',$value);
+                if($value === false || count($value)!=2){
                     $value = array(0=>0, 1=>0);
                 }
                 return new \obray\ipp\types\RangeOfInteger($value[0], $value[1]);
                 break;
             case \obray\ipp\enums\Types::RESOLUTION:
-                $value = explode('x', $value);
-                if(count($value)!=2){
+                $value = $value === null ? false : explode('x', $value);
+                if($value === false || count($value)!=2){
                     $value = array(0=>0, 1=>0);
                 }
                 if(strpos($value[1], 'dpi')!==false){
diff --color -ur a/src/types/Boolean.php b/src/types/Boolean.php
--- a/src/types/Boolean.php	2022-09-08 11:08:04.364359000 +1000
+++ b/src/types/Boolean.php	2022-09-08 11:09:10.427120000 +1000
@@ -15,7 +15,7 @@
         return ($this->value==0)?'false':'true';
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return ($this->value==0)?false:true;
     }
diff --color -ur a/src/types/DateTime.php b/src/types/DateTime.php
--- a/src/types/DateTime.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/DateTime.php	2022-09-08 11:09:32.500342000 +1000
@@ -65,7 +65,7 @@
         return $this->datetime->format("Y-m-d H:i:s.vO");
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->datetime->format("Y-m-d H:i:s.vO");;
     }
diff --color -ur a/src/types/Enum.php b/src/types/Enum.php
--- a/src/types/Enum.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/Enum.php	2022-09-08 11:09:11.287120000 +1000
@@ -43,7 +43,7 @@
         return $this->valueTag;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return str_replace('_','-',strtolower($this->key));
     }
diff --color -ur a/src/types/MemberAttribute.php b/src/types/MemberAttribute.php
--- a/src/types/MemberAttribute.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/MemberAttribute.php	2022-09-08 11:09:50.100342000 +1000
@@ -122,7 +122,7 @@
         return $this;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->memberValue;
     }
diff --color -ur a/src/types/NameWithLanguage.php b/src/types/NameWithLanguage.php
--- a/src/types/NameWithLanguage.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/NameWithLanguage.php	2022-09-08 11:09:12.637120000 +1000
@@ -50,7 +50,7 @@
         return (string)$this->name;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return (string)$this->name->getValue();
     }
diff --color -ur a/src/types/NoVal.php b/src/types/NoVal.php
--- a/src/types/NoVal.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/NoVal.php	2022-09-08 11:09:13.387120000 +1000
@@ -25,7 +25,7 @@
         return NULL;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return NULL;
     }
diff --color -ur a/src/types/RangeOfInteger.php b/src/types/RangeOfInteger.php
--- a/src/types/RangeOfInteger.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/RangeOfInteger.php	2022-09-08 11:09:13.857120000 +1000
@@ -56,7 +56,7 @@
         return $range;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         $range = $this->lowerBound;
         if(strlen($this->upperBound)!==0){
diff --color -ur a/src/types/Resolution.php b/src/types/Resolution.php
--- a/src/types/Resolution.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/Resolution.php	2022-09-08 11:09:14.287120000 +1000
@@ -54,7 +54,7 @@
         return $this->crossFeedDirectionResolution . 'x' . $this->feedDirectionResolution . ' ' . $units;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return (string)$this;
     }
diff --color -ur a/src/types/Unknown.php b/src/types/Unknown.php
--- a/src/types/Unknown.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/Unknown.php	2022-09-08 11:09:15.567120000 +1000
@@ -26,7 +26,7 @@
         return $this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return (string)$this;
     }
diff --color -ur a/src/types/VersionNumber.php b/src/types/VersionNumber.php
--- a/src/types/VersionNumber.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/VersionNumber.php	2022-09-08 11:09:16.407120000 +1000
@@ -36,7 +36,7 @@
 
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->majorVersionNumber . '.' . $this->minorVersionNumber;
     }
diff --color -ur a/src/types/basic/LocalizedString.php b/src/types/basic/LocalizedString.php
--- a/src/types/basic/LocalizedString.php	2022-09-08 11:08:04.374359000 +1000
+++ b/src/types/basic/LocalizedString.php	2022-09-08 11:09:17.147120000 +1000
@@ -57,7 +57,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->value;
     }
diff --color -ur a/src/types/basic/OctetString.php b/src/types/basic/OctetString.php
--- a/src/types/basic/OctetString.php	2022-09-08 11:08:04.384359000 +1000
+++ b/src/types/basic/OctetString.php	2022-09-08 11:09:17.777120000 +1000
@@ -47,7 +47,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return (string)$this->value;
     }
diff --color -ur a/src/types/basic/SignedByte.php b/src/types/basic/SignedByte.php
--- a/src/types/basic/SignedByte.php	2022-09-08 11:08:04.384359000 +1000
+++ b/src/types/basic/SignedByte.php	2022-09-08 11:09:18.447120000 +1000
@@ -50,7 +50,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->value;
     }
diff --color -ur a/src/types/basic/SignedInteger.php b/src/types/basic/SignedInteger.php
--- a/src/types/basic/SignedInteger.php	2022-09-08 11:08:04.384359000 +1000
+++ b/src/types/basic/SignedInteger.php	2022-09-08 11:09:18.957120000 +1000
@@ -50,7 +50,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->value;
     }
diff --color -ur a/src/types/basic/SignedShort.php b/src/types/basic/SignedShort.php
--- a/src/types/basic/SignedShort.php	2022-09-08 11:08:04.384359000 +1000
+++ b/src/types/basic/SignedShort.php	2022-09-08 11:09:19.537120000 +1000
@@ -55,7 +55,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return $this->value;
     }
diff --color -ur a/src/types/basic/USASCIIString.php b/src/types/basic/USASCIIString.php
--- a/src/types/basic/USASCIIString.php	2022-09-08 11:08:04.384359000 +1000
+++ b/src/types/basic/USASCIIString.php	2022-09-08 11:09:20.117120000 +1000
@@ -45,7 +45,7 @@
         return (string)$this->value;
     }
 
-    public function jsonSerialize()
+    public function jsonSerialize(): mixed
     {
         return (string)$this->value;
     }
```

**Comment by nateobray** [comment]
@adam1658, very cool.  I will take a look at your patch, but that's awesome you got it to work!

**Comment by nateobray** [comment]
Ok, I replace the external dependency with php curl request that now seems to work find with php8.1.  In the future I'll add the ability to swap out php curl for guzzle if desired, but this get's it working.

Thanks for the issue!  Let me know if you see anything else.

**Comment by dpslwk** [comment]
fix for curl works, been able to talk to a printer, well I can now call `getJobs()` and `getPrinterAttributes()` anyway, will try a print on Monday

but still full of `PHP Deprecated` warnings looks like `ipp-php81.patch` form @adam1658 is all that would be needed to fix all these, be nice if that can be applied

**Comment by adam1658** [comment]
Thanks @nateobray, I’m glad my ideas helped. Sorry I didn’t have time to do a PR myself.
